# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 865c1d8be5c367ed61fc7d8e2db1bf5e59e2f463976198e95d5bf004351b8dbbe2e5ea8d765289782e1b2aa2f76c78e30cad0e91ead5aee60ee498d96e3a17fe

test:
  secret_key_base: 986f0f3e4ddd903b42275695400307637b932d4a9a6faac0e9ebc7a5c21834d057ad3704c1b0bb7a3bf18271eeb85530220bae1a5e509fbff53aa29605e84a8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
